apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prometheus
  namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
        namespace: dev-platform-team-observability-prometheus
    project: default
    source:
        path: ./prometheus
        repoURL: https://github.com/eedorenko/kalypso-oci-svc-gitops
        targetRevision: dev
        directory:
            recurse: true
            include: '*.yaml'
            exclude: 'kustomization.yaml'
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
        - CreateNamespace=true
